substitutions:
  device_name: switch-schuhschrank
  friendly_name: Schuhschrank
  restore_mode: RESTORE_DEFAULT_OFF

packages:
  remote_package:
    url: https://github.com/mnigbur/esphome-packages
    refresh: 0d
    files: [
      common/homeassistant.yaml,
      hardware/teckin_sp22.yaml
    ]